name: Deploy Terraform 3-Tier Infrastructure

on:
  push:
    branches:
      - main  # Runs this workflow when changes are pushed to the main branch

jobs:
  terraform:
    runs-on: self-hosted  # Uses the self-hosted GitHub Actions runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3  # Fetch the repository code

    - name: Set Up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.0  # Specify the Terraform version

    - name: Terraform Init
      run: terraform init  # Initialize Terraform

    - name: Terraform Validate
      run: terraform validate  # Validate the Terraform configuration

    - name: Terraform Plan
      run: terraform plan -out=tfplan  # Create an execution plan

    - name: Terraform Apply
      run: terraform apply -auto-approve  # Apply the Terraform changes

